<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    
    <title>Circle &mdash; EgFreeCAD 0.1 documentation</title>
    
    <link rel="stylesheet" href="../_static/classic.css" type="text/css" />
    <link rel="stylesheet" href="../_static/pygments.css" type="text/css" />
    
    <script type="text/javascript">
      var DOCUMENTATION_OPTIONS = {
        URL_ROOT:    '../',
        VERSION:     '0.1',
        COLLAPSE_INDEX: false,
        FILE_SUFFIX: '.html',
        HAS_SOURCE:  true
      };
    </script>
    <script type="text/javascript" src="../_static/jquery.js"></script>
    <script type="text/javascript" src="../_static/underscore.js"></script>
    <script type="text/javascript" src="../_static/doctools.js"></script>
    <link rel="top" title="EgFreeCAD 0.1 documentation" href="../index.html" />
    <link rel="up" title="Primitive Examples" href="index.html" />
    <link rel="next" title="Sphere" href="sphere.html" />
    <link rel="prev" title="Box" href="box.html" /> 
  </head>
  <body role="document">
    <div class="related" role="navigation" aria-label="related navigation">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="../genindex.html" title="General Index"
             accesskey="I">index</a></li>
        <li class="right" >
          <a href="sphere.html" title="Sphere"
             accesskey="N">next</a> |</li>
        <li class="right" >
          <a href="box.html" title="Box"
             accesskey="P">previous</a> |</li>
        <li class="nav-item nav-item-0"><a href="../index.html">EgFreeCAD 0.1 documentation</a> &raquo;</li>
          <li class="nav-item nav-item-1"><a href="index.html" accesskey="U">Primitive Examples</a> &raquo;</li> 
      </ul>
    </div>  

    <div class="document">
      <div class="documentwrapper">
        <div class="bodywrapper">
          <div class="body" role="main">
            
  <div class="section" id="circle">
<span id="index-0"></span><h1>Circle<a class="headerlink" href="#circle" title="Permalink to this headline">Â¶</a></h1>
<p>The default <code class="xref py py-func docutils literal"><span class="pre">Part.makeCircle(r)()</span></code> produces a circular line on the
XY plane with radius r. (A one dimensional object embedded in a two
dimensional plane in three dimensional space).
The function <code class="xref py py-func docutils literal"><span class="pre">Part.Circle(r)()</span></code> does essentially the same thing but takes
arguments for the center, normal and radius, and has to be converted to a
shape object.</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">c</span> <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">makeCircle</span><span class="p">(</span><span class="mi">5</span><span class="p">)</span>
<span class="c1">#Part.show(c)</span>
<span class="n">c2</span> <span class="o">=</span> <span class="n">c</span><span class="o">.</span><span class="n">copy</span><span class="p">()</span>
<span class="n">testEqual</span><span class="p">(</span><span class="n">c</span><span class="p">,</span> <span class="n">c2</span><span class="p">)</span>
<span class="n">testNotEqual</span><span class="p">(</span><span class="n">c</span><span class="p">,</span> <span class="n">Part</span><span class="o">.</span><span class="n">makeCircle</span><span class="p">(</span><span class="mi">6</span><span class="p">))</span>

<span class="n">testEqual</span><span class="p">(</span><span class="n">c</span><span class="p">,</span> <span class="n">Part</span><span class="o">.</span><span class="n">Circle</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">z</span><span class="p">,</span> <span class="mi">5</span><span class="p">)</span><span class="o">.</span><span class="n">toShape</span><span class="p">()</span> <span class="p">)</span>
</pre></div>
</div>
<p>A circle has attributes that can be checked as follows.</p>
<div class="highlight-python"><div class="highlight"><pre><span class="k">print</span><span class="p">(</span><span class="n">c</span><span class="o">.</span><span class="n">Curve</span><span class="o">.</span><span class="n">Radius</span> <span class="o">==</span> <span class="mf">5.0</span><span class="p">)</span>
<span class="k">print</span><span class="p">(</span><span class="n">c</span><span class="o">.</span><span class="n">Curve</span><span class="o">.</span><span class="n">Center</span> <span class="o">==</span> <span class="n">o</span> <span class="p">)</span>
<span class="k">print</span><span class="p">(</span><span class="n">c</span><span class="o">.</span><span class="n">Curve</span><span class="o">.</span><span class="n">Axis</span>   <span class="o">==</span> <span class="n">z</span> <span class="p">)</span>
</pre></div>
</div>
<div class="highlight-none"><div class="highlight"><pre>True
True
True
</pre></div>
</div>
<p>Within its plane, a circle is symmetic around its center, so this circle can be
rotated any number of degrees around the Z-axis and produces an equal object</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">c2</span><span class="o">.</span><span class="n">rotate</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">z</span><span class="p">,</span> <span class="mi">180</span><span class="p">)</span>
<span class="n">testEqual</span><span class="p">(</span><span class="n">c</span><span class="p">,</span> <span class="n">c2</span><span class="p">)</span>
<span class="n">c2</span><span class="o">.</span><span class="n">rotate</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">z</span><span class="p">,</span> <span class="mi">90</span><span class="p">)</span>
<span class="n">testEqual</span><span class="p">(</span><span class="n">c</span><span class="p">,</span> <span class="n">c2</span><span class="p">)</span>
<span class="n">c2</span><span class="o">.</span><span class="n">rotate</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">z</span><span class="p">,</span> <span class="mi">33</span><span class="p">)</span>
<span class="n">testEqual</span><span class="p">(</span><span class="n">c</span><span class="p">,</span> <span class="n">c2</span><span class="p">)</span>
</pre></div>
</div>
<p>but translation produces an object that is not equal.</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">c2</span><span class="o">.</span><span class="n">translate</span><span class="p">(</span><span class="n">Vector</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span><span class="mi">0</span><span class="p">,</span><span class="mi">10</span><span class="p">))</span>
<span class="n">testNotEqual</span><span class="p">(</span><span class="n">c</span><span class="p">,</span> <span class="n">c2</span><span class="p">)</span>
</pre></div>
</div>
<p>This circle is centered at the origin and is on the plane
normal to z axis. A circle has one edge and no faces, properties that can
be checked.</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">C</span> <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">makeCircle</span><span class="p">(</span><span class="mi">10</span><span class="p">)</span>
<span class="k">print</span><span class="p">(</span> <span class="nb">len</span><span class="p">(</span><span class="n">C</span><span class="o">.</span><span class="n">Edges</span><span class="p">)</span> <span class="p">)</span>
<span class="k">print</span><span class="p">(</span> <span class="nb">len</span><span class="p">(</span><span class="n">C</span><span class="o">.</span><span class="n">Faces</span><span class="p">)</span> <span class="p">)</span>
<span class="k">print</span><span class="p">(</span> <span class="nb">len</span><span class="p">(</span><span class="n">C</span><span class="o">.</span><span class="n">Solids</span><span class="p">)</span> <span class="p">)</span>
</pre></div>
</div>
<div class="highlight-none"><div class="highlight"><pre>1
0
0
</pre></div>
</div>
<p>When constructing a face (two dimensional object) from a circle (one
dimensional object) it is usually important that the circle is not a partial
circle, that is, it forms a complete closed loop. This is also a property
that can be checked.</p>
<div class="highlight-python"><div class="highlight"><pre><span class="k">print</span><span class="p">(</span> <span class="n">C</span><span class="o">.</span><span class="n">isClosed</span><span class="p">()</span> <span class="p">)</span>
</pre></div>
</div>
<div class="highlight-none"><div class="highlight"><pre>True
</pre></div>
</div>
<p>A face can be constructed by filling in the circle. For some reason this
needs to be converted to a wire first.</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">C2</span> <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">Face</span><span class="p">(</span><span class="n">Part</span><span class="o">.</span><span class="n">Wire</span><span class="p">(</span><span class="n">C</span><span class="p">))</span>
<span class="k">print</span><span class="p">(</span> <span class="n">C2</span><span class="o">.</span><span class="n">ShapeType</span> <span class="p">)</span>
<span class="k">print</span><span class="p">(</span> <span class="nb">len</span><span class="p">(</span><span class="n">C2</span><span class="o">.</span><span class="n">Faces</span><span class="p">)</span> <span class="p">)</span>
<span class="k">print</span><span class="p">(</span> <span class="nb">len</span><span class="p">(</span><span class="n">C2</span><span class="o">.</span><span class="n">Solids</span><span class="p">)</span> <span class="p">)</span>
<span class="c1">#Part.show(C2)</span>
</pre></div>
</div>
<div class="highlight-none"><div class="highlight"><pre>Face
1
0
</pre></div>
</div>
</div>


          </div>
        </div>
      </div>
      <div class="sphinxsidebar" role="navigation" aria-label="main navigation">
        <div class="sphinxsidebarwrapper">
  <h4>Previous topic</h4>
  <p class="topless"><a href="box.html"
                        title="previous chapter">Box</a></p>
  <h4>Next topic</h4>
  <p class="topless"><a href="sphere.html"
                        title="next chapter">Sphere</a></p>
  <div role="note" aria-label="source link">
    <h3>This Page</h3>
    <ul class="this-page-menu">
      <li><a href="../_sources/Primitives/circle.txt"
            rel="nofollow">Show Source</a></li>
    </ul>
   </div>
<div id="searchbox" style="display: none" role="search">
  <h3>Quick search</h3>
    <form class="search" action="../search.html" method="get">
      <input type="text" name="q" />
      <input type="submit" value="Go" />
      <input type="hidden" name="check_keywords" value="yes" />
      <input type="hidden" name="area" value="default" />
    </form>
    <p class="searchtip" style="font-size: 90%">
    Enter search terms or a module, class or function name.
    </p>
</div>
<script type="text/javascript">$('#searchbox').show(0);</script>
        </div>
      </div>
      <div class="clearer"></div>
    </div>
    <div class="related" role="navigation" aria-label="related navigation">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="../genindex.html" title="General Index"
             >index</a></li>
        <li class="right" >
          <a href="sphere.html" title="Sphere"
             >next</a> |</li>
        <li class="right" >
          <a href="box.html" title="Box"
             >previous</a> |</li>
        <li class="nav-item nav-item-0"><a href="../index.html">EgFreeCAD 0.1 documentation</a> &raquo;</li>
          <li class="nav-item nav-item-1"><a href="index.html" >Primitive Examples</a> &raquo;</li> 
      </ul>
    </div>
    <div class="footer" role="contentinfo">
        &copy; Copyright 2018, 2019, Paul Gilbert.
      Last updated on May 21, 2019.
      Created using <a href="http://sphinx-doc.org/">Sphinx</a> 1.3.6.
    </div>
  </body>
</html>