<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    
    <title>Sphere &mdash; EgFreeCAD 0.1 documentation</title>
    
    <link rel="stylesheet" href="../_static/classic.css" type="text/css" />
    <link rel="stylesheet" href="../_static/pygments.css" type="text/css" />
    
    <script type="text/javascript">
      var DOCUMENTATION_OPTIONS = {
        URL_ROOT:    '../',
        VERSION:     '0.1',
        COLLAPSE_INDEX: false,
        FILE_SUFFIX: '.html',
        HAS_SOURCE:  true
      };
    </script>
    <script type="text/javascript" src="../_static/jquery.js"></script>
    <script type="text/javascript" src="../_static/underscore.js"></script>
    <script type="text/javascript" src="../_static/doctools.js"></script>
    <link rel="top" title="EgFreeCAD 0.1 documentation" href="../index.html" />
    <link rel="up" title="Primitive Examples" href="index.html" />
    <link rel="next" title="Ellipse" href="ellipse.html" />
    <link rel="prev" title="Circle" href="circle.html" /> 
  </head>
  <body role="document">
    <div class="related" role="navigation" aria-label="related navigation">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="../genindex.html" title="General Index"
             accesskey="I">index</a></li>
        <li class="right" >
          <a href="ellipse.html" title="Ellipse"
             accesskey="N">next</a> |</li>
        <li class="right" >
          <a href="circle.html" title="Circle"
             accesskey="P">previous</a> |</li>
        <li class="nav-item nav-item-0"><a href="../index.html">EgFreeCAD 0.1 documentation</a> &raquo;</li>
          <li class="nav-item nav-item-1"><a href="index.html" accesskey="U">Primitive Examples</a> &raquo;</li> 
      </ul>
    </div>  

    <div class="document">
      <div class="documentwrapper">
        <div class="bodywrapper">
          <div class="body" role="main">
            
  <div class="section" id="sphere">
<span id="index-0"></span><h1>Sphere<a class="headerlink" href="#sphere" title="Permalink to this headline">Â¶</a></h1>
<p>FreeCAD <code class="xref py py-func docutils literal"><span class="pre">Part.Sphere()</span></code> produces a two dimensional curved
surface (face) embedded in three dimensional space (R<sup>3</sup>).
(The mathematical topology of the object is S<sup>2</sup> ).
The fact that this sphere is hollow can be seen by displaying with a piece
cut out, or checked by verifying that the object contains no solids.</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">S2</span> <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">Sphere</span><span class="p">()</span><span class="o">.</span><span class="n">toShape</span><span class="p">()</span>
<span class="c1">#Part.show(S2)</span>
<span class="k">print</span><span class="p">(</span> <span class="n">S2</span><span class="o">.</span><span class="n">ShapeType</span> <span class="p">)</span>  <span class="c1">#Face</span>
<span class="k">print</span><span class="p">(</span> <span class="nb">len</span><span class="p">(</span><span class="n">S2</span><span class="o">.</span><span class="n">Solids</span><span class="p">))</span> <span class="c1"># 0</span>

<span class="c1"># Part.show(s2.cut(Part.makeBox(10,10,10)))</span>
</pre></div>
</div>
<div class="highlight-none"><div class="highlight"><pre>Face
0
</pre></div>
</div>
<p>Below concentrates on solid objects. Notice the difference between
<code class="xref py py-func docutils literal"><span class="pre">Part.Sphere()</span></code> which is hollow and <code class="xref py py-func docutils literal"><span class="pre">Part.makeSphere()</span></code>
which is solid.
Solid objects will be more interesting for things like 3D printing.</p>
<p>The default <code class="xref py py-obj docutils literal"><span class="pre">Part.makeSphere(r)</span></code> produces a solid sphere centered
at the origin with radius r. This is a three dimensional object.
A sphere can be rotated in any direction about its
center and produce an equal object, but translation gives an object that is
not equal.</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">s</span> <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">makeSphere</span><span class="p">(</span><span class="mi">10</span><span class="p">)</span>
<span class="c1">#Part.show(s.cut(Part.makeBox(10,10,10)))</span>
<span class="k">print</span><span class="p">(</span><span class="n">s</span><span class="o">.</span><span class="n">ShapeType</span><span class="p">)</span>

<span class="n">sr</span> <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">makeSphere</span><span class="p">(</span><span class="mi">10</span><span class="p">)</span>
<span class="n">sr</span><span class="o">.</span><span class="n">rotate</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">z</span><span class="p">,</span> <span class="mi">180</span><span class="p">)</span>
<span class="n">testEqual</span><span class="p">(</span><span class="n">s</span><span class="p">,</span> <span class="n">sr</span><span class="p">)</span>

<span class="n">sr</span><span class="o">.</span><span class="n">translate</span><span class="p">(</span><span class="n">Vector</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span><span class="mi">0</span><span class="p">,</span><span class="mi">10</span><span class="p">))</span>
<span class="n">testNotEqual</span><span class="p">(</span><span class="n">s</span><span class="p">,</span> <span class="n">sr</span><span class="p">)</span>

<span class="n">testNotEqual</span><span class="p">(</span><span class="n">s</span><span class="p">,</span> <span class="n">Part</span><span class="o">.</span><span class="n">makeSphere</span><span class="p">(</span><span class="mi">9</span><span class="p">))</span>
</pre></div>
</div>
<div class="highlight-none"><div class="highlight"><pre>Solid
</pre></div>
</div>
<p>A sphere object has edges, faces and solids.</p>
<div class="highlight-python"><div class="highlight"><pre><span class="k">print</span><span class="p">(</span><span class="nb">len</span><span class="p">(</span><span class="n">s</span><span class="o">.</span><span class="n">Edges</span><span class="p">))</span>
<span class="k">print</span><span class="p">(</span><span class="nb">len</span><span class="p">(</span><span class="n">s</span><span class="o">.</span><span class="n">Faces</span><span class="p">))</span>
<span class="k">print</span><span class="p">(</span> <span class="nb">len</span><span class="p">(</span><span class="n">s</span><span class="o">.</span><span class="n">Solids</span><span class="p">))</span>
</pre></div>
</div>
<div class="highlight-none"><div class="highlight"><pre>3
1
1
</pre></div>
</div>
<p id="index-1">A sphere can also be constructed by revolving a circle.
A full circle revolved 360 degrees covers the sphere twice over, which causes
anomolies according to the help for <code class="xref py py-func docutils literal"><span class="pre">revolve()</span></code>.
Revolving 180 degrees is better.</p>
<p>(There is an anomaly here. makeSphere gives ShapeType &#8216;Solid&#8217; whereas Circle
gives ShapeType &#8216;Face&#8217;, but cutting leaves an empty object. See Puzzles.)</p>
<p>Revolving a full circle seems broken. Intuitively this may seem like the
most obvious way to proceed, but does not work.</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">c10</span> <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">Circle</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">z</span><span class="p">,</span> <span class="mi">10</span><span class="p">)</span>

<span class="c1"># Part.show(c10.toShape())</span>
<span class="c1"># Part.show(Part.makeCircle(10))</span>

<span class="k">print</span><span class="p">(</span> <span class="n">c10</span><span class="o">.</span><span class="n">toShape</span><span class="p">()</span><span class="o">.</span><span class="n">revolve</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">x</span><span class="p">,</span> <span class="mi">180</span><span class="p">)</span><span class="o">.</span><span class="n">isValid</span><span class="p">()</span> <span class="p">)</span> <span class="c1"># False</span>
<span class="k">print</span><span class="p">(</span> <span class="n">c10</span><span class="o">.</span><span class="n">toShape</span><span class="p">()</span><span class="o">.</span><span class="n">revolve</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">y</span><span class="p">,</span> <span class="mi">180</span><span class="p">)</span><span class="o">.</span><span class="n">isValid</span><span class="p">()</span> <span class="p">)</span> <span class="c1"># False</span>
<span class="k">print</span><span class="p">(</span> <span class="n">c10</span><span class="o">.</span><span class="n">toShape</span><span class="p">()</span><span class="o">.</span><span class="n">revolve</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">z</span><span class="p">,</span> <span class="mi">180</span><span class="p">)</span><span class="o">.</span><span class="n">isValid</span><span class="p">()</span> <span class="p">)</span> <span class="c1"># True but flat (z is norm)</span>
<span class="c1"># Part.show(c10.toShape().revolve(o, z, 180))</span>
</pre></div>
</div>
<div class="highlight-none"><div class="highlight"><pre>False
False
True
</pre></div>
</div>
<p>A solid sphere can also be constructed by revolving a half circle line and
filling in the result to make a solid. According to the help for
<code class="xref py py-func docutils literal"><span class="pre">revolve()</span></code> this is
better than revolving a full circle. (This is an algorithmic
improvement, not a theoretical difference.). <code class="xref py py-obj docutils literal"><span class="pre">LastParameter</span></code>
for a circle is 2 * pi radians, so <code class="xref py py-obj docutils literal"><span class="pre">h10</span></code> in
the next is a half circle on the X-Y plane.
Revolving around the Z-axis results in a flat full circle, filled in to make an
object of ShapeType &#8216;Face&#8217;.
Revolving around the X-axis produces an object that is not valid. I think this is
because of the problem mentioned in the help for revolve, the meshing algorithm
does not like to rotate around a point where there is no vertex.
The Y-axis goes through both vertexes and revolving around it works well.</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">c10</span> <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">Circle</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">z</span><span class="p">,</span> <span class="mi">10</span><span class="p">)</span>
<span class="n">h10</span> <span class="o">=</span> <span class="n">c10</span><span class="o">.</span><span class="n">toShape</span><span class="p">(</span><span class="n">c10</span><span class="o">.</span><span class="n">LastParameter</span><span class="o">/</span><span class="mi">4</span><span class="p">,</span> <span class="mi">3</span><span class="o">*</span><span class="n">c10</span><span class="o">.</span><span class="n">LastParameter</span><span class="o">/</span><span class="mi">4</span><span class="p">)</span>
<span class="k">print</span><span class="p">(</span> <span class="n">h10</span><span class="o">.</span><span class="n">ShapeType</span> <span class="p">)</span>
<span class="c1"># Part.show(h10)   # unfilled half circle on X-Y plane</span>

<span class="k">print</span><span class="p">(</span> <span class="n">h10</span><span class="o">.</span><span class="n">revolve</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">z</span><span class="p">,</span> <span class="mi">360</span><span class="p">)</span><span class="o">.</span><span class="n">isValid</span><span class="p">()</span> <span class="p">)</span>     <span class="c1"># True</span>
<span class="k">print</span><span class="p">(</span> <span class="n">h10</span><span class="o">.</span><span class="n">revolve</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">x</span><span class="p">,</span> <span class="mi">360</span><span class="p">)</span><span class="o">.</span><span class="n">isValid</span><span class="p">()</span> <span class="p">)</span>     <span class="c1"># False</span>
<span class="k">print</span><span class="p">(</span> <span class="n">h10</span><span class="o">.</span><span class="n">revolve</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">y</span><span class="p">,</span> <span class="mi">360</span><span class="p">)</span><span class="o">.</span><span class="n">isValid</span><span class="p">()</span> <span class="p">)</span>     <span class="c1"># True</span>

<span class="n">sf10</span> <span class="o">=</span> <span class="n">h10</span><span class="o">.</span><span class="n">revolve</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">y</span><span class="p">,</span> <span class="mi">360</span><span class="p">)</span>
<span class="k">print</span><span class="p">(</span> <span class="n">sf10</span><span class="o">.</span><span class="n">ShapeType</span> <span class="p">)</span>
<span class="c1"># Part.show(sf10)</span>

<span class="n">s10</span> <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">makeSolid</span><span class="p">(</span><span class="n">Part</span><span class="o">.</span><span class="n">makeShell</span><span class="p">([</span><span class="n">sf10</span><span class="p">]))</span>
<span class="c1"># Part.show(s10)</span>
<span class="k">print</span><span class="p">(</span> <span class="n">s10</span><span class="o">.</span><span class="n">ShapeType</span> <span class="p">)</span>
<span class="k">print</span><span class="p">(</span> <span class="nb">len</span><span class="p">(</span><span class="n">s10</span><span class="o">.</span><span class="n">Solids</span><span class="p">)</span> <span class="p">)</span>

<span class="k">print</span><span class="p">(</span> <span class="n">s10</span><span class="o">.</span><span class="n">cut</span><span class="p">(</span><span class="n">s</span><span class="p">)</span><span class="o">.</span><span class="n">isValid</span><span class="p">()</span> <span class="p">)</span> <span class="c1"># True</span>
<span class="k">print</span><span class="p">(</span> <span class="n">s</span><span class="o">.</span><span class="n">cut</span><span class="p">(</span><span class="n">s10</span><span class="p">)</span><span class="o">.</span><span class="n">isValid</span><span class="p">()</span> <span class="p">)</span> <span class="c1"># True</span>

<span class="c1">#testEqual(s, s10) # this test seems a bit fragile</span>

<span class="c1"># Part.show(s.cut(Part.makeBox(10,10,10)))</span>
<span class="c1"># Part.show(s10.cut(Part.makeBox(10,10,10)))</span>
<span class="c1"># Part.show(s10.cut(s))</span>
<span class="c1"># Part.show(s.cut(s10))</span>
<span class="c1"># Part.show((s10.cut(s)).cut(Part.makeBox(10,10,10)))</span>
<span class="c1"># Part.show((s.cut(s10)).cut(Part.makeBox(10,10,10)))</span>
</pre></div>
</div>
<div class="highlight-none"><div class="highlight"><pre>Edge
True
False
True
Face
Solid
1
True
True
</pre></div>
</div>
<p>To support speculation about difficulty for the meshing algorithm, this example
selects a different section of the circle and rotates successfully around
the X-axis.</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">c10</span> <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">Circle</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">z</span><span class="p">,</span> <span class="mi">10</span><span class="p">)</span>
<span class="k">print</span><span class="p">(</span> <span class="n">c10</span><span class="o">.</span><span class="n">toShape</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="n">c10</span><span class="o">.</span><span class="n">LastParameter</span><span class="o">/</span><span class="mi">2</span><span class="p">)</span><span class="o">.</span><span class="n">revolve</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">x</span><span class="p">,</span> <span class="mi">360</span><span class="p">)</span><span class="o">.</span><span class="n">isValid</span><span class="p">()</span> <span class="p">)</span><span class="c1"># True</span>
<span class="n">s10x</span> <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">makeSolid</span><span class="p">(</span><span class="n">Part</span><span class="o">.</span><span class="n">makeShell</span><span class="p">([</span><span class="n">c10</span><span class="o">.</span><span class="n">toShape</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span>
                 <span class="n">c10</span><span class="o">.</span><span class="n">LastParameter</span><span class="o">/</span><span class="mi">2</span><span class="p">)</span><span class="o">.</span><span class="n">revolve</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">x</span><span class="p">,</span> <span class="mi">360</span><span class="p">)]))</span>
<span class="k">print</span><span class="p">(</span> <span class="n">s10x</span><span class="o">.</span><span class="n">ShapeType</span> <span class="p">)</span>
<span class="c1"># Part.show(s10x)</span>
<span class="n">testEqual</span><span class="p">(</span><span class="n">s</span><span class="p">,</span> <span class="n">s10x</span><span class="p">)</span>
</pre></div>
</div>
<div class="highlight-none"><div class="highlight"><pre>True
Solid
</pre></div>
</div>
<p>And this example creates the circle on the Y-Z plane and
selects a circle section that rotates successfully around the Z-axis.</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">c10z</span> <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">Circle</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">x</span><span class="p">,</span> <span class="mi">10</span><span class="p">)</span>
<span class="k">print</span><span class="p">(</span> <span class="n">c10z</span><span class="o">.</span><span class="n">toShape</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="n">c10z</span><span class="o">.</span><span class="n">LastParameter</span><span class="o">/</span><span class="mi">2</span><span class="p">)</span><span class="o">.</span><span class="n">revolve</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">x</span><span class="p">,</span> <span class="mi">360</span><span class="p">)</span><span class="o">.</span><span class="n">isValid</span><span class="p">()</span> <span class="p">)</span><span class="c1"># True</span>

<span class="n">s10z</span> <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">makeSolid</span><span class="p">(</span><span class="n">Part</span><span class="o">.</span><span class="n">makeShell</span><span class="p">([</span>
          <span class="n">c10z</span><span class="o">.</span><span class="n">toShape</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="n">c10z</span><span class="o">.</span><span class="n">LastParameter</span><span class="o">/</span><span class="mi">2</span><span class="p">)</span><span class="o">.</span><span class="n">revolve</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">z</span><span class="p">,</span> <span class="mi">360</span><span class="p">)</span>  <span class="p">]))</span>
<span class="k">print</span><span class="p">(</span> <span class="n">s10z</span><span class="o">.</span><span class="n">ShapeType</span> <span class="p">)</span>
<span class="c1"># Part.show(s10z)</span>
<span class="n">testEqual</span><span class="p">(</span><span class="n">s</span><span class="p">,</span> <span class="n">s10z</span><span class="p">)</span>
</pre></div>
</div>
<div class="highlight-none"><div class="highlight"><pre>True
Solid
</pre></div>
</div>
<span class="target" id="index-2"></span><p id="index-3">While <code class="xref py py-func docutils literal"><span class="pre">Part.makeSphere()</span></code> will generally be easier to use to make a sphere,
or portions of it, an arc can be used to make different rotation profiles.
The next example shows making a sphere using <code class="xref py py-func docutils literal"><span class="pre">Part.arc()</span></code>
and <code class="xref py py-func docutils literal"><span class="pre">Part.makeRevolution()</span></code> so easy test comparisons are
possible, but that will generally not be the most interesting rotation profile.</p>
<p><code class="xref py py-func docutils literal"><span class="pre">Part.makeRevolution()</span></code> takes 7 arguments.
(Prior to FreeCAD 0.19,  if the first argument was Part.Shape object then it was
used to determine the ShapeType and only the 6 first arguments were supported.)</p>
<p>Notice also that the angle, center,
and axis arguments are in a different order from the <code class="xref py py-func docutils literal"><span class="pre">revolve()</span></code> method.</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">arc</span> <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">Arc</span><span class="p">(</span><span class="o">-</span><span class="mi">10</span><span class="o">*</span><span class="n">z</span><span class="p">,</span> <span class="mi">10</span><span class="o">*</span><span class="n">x</span><span class="p">,</span> <span class="mi">10</span><span class="o">*</span><span class="n">z</span><span class="p">)</span>
<span class="c1">#Part.show(arc.toShape())</span>

<span class="n">aS</span> <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">makeRevolution</span><span class="p">(</span><span class="n">arc</span><span class="p">,</span> <span class="n">arc</span><span class="o">.</span><span class="n">FirstParameter</span><span class="p">,</span> <span class="n">arc</span><span class="o">.</span><span class="n">LastParameter</span><span class="p">,</span>
              <span class="mi">360</span><span class="p">,</span> <span class="n">o</span><span class="p">,</span> <span class="n">z</span><span class="p">,</span> <span class="n">Part</span><span class="o">.</span><span class="n">Solid</span><span class="p">)</span>
<span class="k">print</span><span class="p">(</span><span class="n">aS</span><span class="o">.</span><span class="n">isClosed</span><span class="p">()</span> <span class="p">)</span>  <span class="c1">#True</span>
<span class="k">print</span><span class="p">(</span><span class="n">aS</span><span class="o">.</span><span class="n">isValid</span><span class="p">()</span> <span class="p">)</span>   <span class="c1">#True</span>
<span class="k">print</span><span class="p">(</span> <span class="n">aS</span><span class="o">.</span><span class="n">ShapeType</span> <span class="p">)</span>  <span class="c1">#Solid</span>
<span class="c1">#Part.show(aS)</span>

<span class="n">Part</span><span class="o">.</span><span class="n">makeRevolution</span><span class="p">(</span><span class="n">arc</span><span class="p">,</span> <span class="n">arc</span><span class="o">.</span><span class="n">FirstParameter</span><span class="p">,</span> <span class="n">arc</span><span class="o">.</span><span class="n">LastParameter</span><span class="p">,</span>
              <span class="mi">360</span><span class="p">,</span> <span class="n">o</span><span class="p">,</span> <span class="n">z</span><span class="p">,</span> <span class="n">Part</span><span class="o">.</span><span class="n">Face</span><span class="p">)</span><span class="o">.</span><span class="n">ShapeType</span>  <span class="c1"># Face</span>

<span class="c1">#Part.show(aS)</span>

<span class="n">testEqual</span><span class="p">(</span><span class="n">s</span><span class="p">,</span> <span class="n">aS</span><span class="p">)</span>

<span class="n">testEqual</span><span class="p">(</span><span class="n">s</span><span class="p">,</span> <span class="n">Part</span><span class="o">.</span><span class="n">makeRevolution</span><span class="p">(</span><span class="n">arc</span><span class="o">.</span><span class="n">toShape</span><span class="p">(),</span>
           <span class="n">arc</span><span class="o">.</span><span class="n">FirstParameter</span><span class="p">,</span> <span class="n">arc</span><span class="o">.</span><span class="n">LastParameter</span><span class="p">,</span> <span class="mi">360</span><span class="p">,</span> <span class="n">o</span><span class="p">,</span> <span class="n">z</span><span class="p">)</span> <span class="p">)</span>

<span class="c1"># This should work in 0.19</span>
<span class="c1">#if (100* float(FreeCAD.Version()[0]) + float(FreeCAD.Version()[1]) &gt;= 19.0 ):</span>
<span class="c1">#testEqual(s, Part.makeRevolution(arc.toShape(),</span>
<span class="c1">#           arc.FirstParameter, arc.LastParameter, 360, o, z, Part.Solid) )</span>
<span class="c1">#testEqual(s, Part.makeRevolution(arc.toShape(),</span>
<span class="c1">#           arc.FirstParameter, arc.LastParameter, 360, o, z, Part.Solid) )</span>
<span class="c1">#if (100* float(FreeCAD.Version()[0]) + float(FreeCAD.Version()[1]) &gt;= 19.0 ):</span>
<span class="c1">#  aSe = Part.makeRevolution(arc.toShape(), arc.FirstParameter, arc.LastParameter,</span>
<span class="c1">#              360, o, z, Part.Face).ShapeType  #Face</span>
</pre></div>
</div>
<div class="highlight-none"><div class="highlight"><pre>True
True
Solid
</pre></div>
</div>
<p>It is important that the shape created by <code class="xref py py-func docutils literal"><span class="pre">Part.makeRevolution()</span></code> is closed
or the result is not likely to be valid, and the problem is not immediately indicated
unless you check. Subsequent use of the returned object is likely to be problematic
but the source of the problem may not be obvious.</p>
<p>A revolved Face object produces a solid but beware that revolving other object will
not produce solids. (More on this further below.)</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">arcS</span> <span class="o">=</span> <span class="n">arc</span><span class="o">.</span><span class="n">toShape</span><span class="p">()</span><span class="o">.</span><span class="n">revolve</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">z</span><span class="p">,</span> <span class="mi">360</span><span class="p">)</span>
<span class="k">print</span><span class="p">(</span> <span class="n">arcS</span><span class="o">.</span><span class="n">ShapeType</span> <span class="p">)</span>
<span class="c1">#Part.makeSolid(Part.makeShell([arcS]))</span>
<span class="c1">#Part.makeSolid(arcS)</span>
<span class="c1">#Part.makeFilledFace(arcS.Edges)</span>

<span class="n">testNotEqual</span><span class="p">(</span><span class="n">s</span><span class="p">,</span> <span class="n">arcS</span> <span class="p">)</span>
</pre></div>
</div>
<div class="highlight-none"><div class="highlight"><pre>Face
</pre></div>
</div>
<p>py:func:<cite>Part.makeRevolution</cite> can also be used to make a solid
hemisphere. It is used next to illustrate mirror and fuse.</p>
<p>py:obj:<a href="#id1"><span class="problematic" id="id2">`</span></a>Part.makeSphere(radius, center, axis, fromLatitude, toLatitude, rotationAngle)
where fromLatitude is angle to start of sweep, measured fom a normal to the axis,
toLatitude is angle to end of sweep, measured from a normal to the axis,
and rotationAngle is the circular sweep around the axis. Angles in degrees.</p>
<div class="highlight-python"><div class="highlight"><pre><span class="c1">#Part.show(Part.makeSphere(10, o, y, 45, 90, 360))</span>
<span class="c1">#Part.show(Part.makeSphere(10, o, y, 45, 60, 360))</span>
<span class="c1">#Part.show(Part.makeSphere(10, o, y, 45, 60, 270))</span>

<span class="n">hS</span>  <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">makeSphere</span><span class="p">(</span><span class="mi">10</span><span class="p">,</span> <span class="n">o</span><span class="p">,</span> <span class="n">y</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">90</span><span class="p">,</span> <span class="mi">360</span><span class="p">)</span>
<span class="n">hSm</span> <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">makeSphere</span><span class="p">(</span><span class="mi">10</span><span class="p">,</span> <span class="n">o</span><span class="p">,</span> <span class="o">-</span><span class="n">y</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">90</span><span class="p">,</span> <span class="mi">360</span><span class="p">)</span>

<span class="n">testEqual</span><span class="p">(</span><span class="n">s</span><span class="p">,</span> <span class="n">hS</span><span class="o">.</span><span class="n">fuse</span><span class="p">(</span><span class="n">hSm</span><span class="p">)</span>  <span class="p">)</span>
<span class="n">testEqual</span><span class="p">(</span><span class="n">hSm</span><span class="p">,</span> <span class="n">hS</span><span class="o">.</span><span class="n">mirror</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">y</span><span class="p">)</span> <span class="p">)</span>
<span class="n">testEqual</span><span class="p">(</span><span class="n">s</span><span class="p">,</span> <span class="n">hS</span><span class="o">.</span><span class="n">fuse</span><span class="p">(</span><span class="n">hS</span><span class="o">.</span><span class="n">mirror</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">y</span><span class="p">))</span>  <span class="p">)</span>
<span class="n">testEqual</span><span class="p">(</span><span class="n">s</span><span class="p">,</span> <span class="n">hS</span><span class="o">.</span><span class="n">mirror</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">y</span><span class="p">)</span><span class="o">.</span><span class="n">fuse</span><span class="p">(</span><span class="n">hS</span><span class="p">)</span>  <span class="p">)</span>

<span class="c1">#Part.show(hS)</span>
<span class="c1">#Part.show(hSm)</span>
<span class="c1">#Part.show(hS.fuse(hSm) )</span>

<span class="n">arc</span> <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">Arc</span><span class="p">(</span><span class="o">-</span><span class="mi">10</span><span class="o">*</span><span class="n">z</span><span class="p">,</span> <span class="mi">10</span><span class="o">*</span><span class="n">x</span><span class="p">,</span> <span class="mi">10</span><span class="o">*</span><span class="n">z</span><span class="p">)</span>
<span class="n">hSr</span> <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">makeRevolution</span><span class="p">(</span><span class="n">arc</span><span class="p">,</span>
           <span class="n">arc</span><span class="o">.</span><span class="n">FirstParameter</span><span class="p">,</span> <span class="n">arc</span><span class="o">.</span><span class="n">LastParameter</span><span class="p">,</span> <span class="mi">180</span><span class="p">,</span> <span class="n">o</span><span class="p">,</span> <span class="n">z</span><span class="p">,</span> <span class="n">Part</span><span class="o">.</span><span class="n">Solid</span><span class="p">)</span>

<span class="k">print</span><span class="p">(</span> <span class="n">hSr</span><span class="o">.</span><span class="n">isClosed</span><span class="p">()</span> <span class="p">)</span>  <span class="c1"># True</span>
<span class="k">print</span><span class="p">(</span> <span class="n">hSr</span><span class="o">.</span><span class="n">isValid</span><span class="p">()</span> <span class="p">)</span>   <span class="c1"># True</span>
<span class="k">print</span><span class="p">(</span> <span class="n">hSr</span><span class="o">.</span><span class="n">ShapeType</span> <span class="p">)</span>   <span class="c1"># Solid</span>
<span class="c1">#Part.show(hSr)</span>

<span class="n">testEqual</span><span class="p">(</span><span class="n">hS</span><span class="p">,</span> <span class="n">hSr</span> <span class="p">)</span>
<span class="n">testEqual</span><span class="p">(</span><span class="n">hS</span><span class="o">.</span><span class="n">mirror</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">y</span><span class="p">),</span> <span class="n">hSr</span><span class="o">.</span><span class="n">mirror</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">y</span><span class="p">)</span> <span class="p">)</span>
<span class="n">testEqual</span><span class="p">(</span><span class="n">s</span><span class="p">,</span> <span class="n">hS</span><span class="o">.</span><span class="n">mirror</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">y</span><span class="p">)</span><span class="o">.</span><span class="n">fuse</span><span class="p">(</span><span class="n">hSr</span><span class="p">)</span> <span class="p">)</span>
<span class="n">testEqual</span><span class="p">(</span><span class="n">s</span><span class="p">,</span> <span class="n">hSr</span><span class="o">.</span><span class="n">mirror</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">y</span><span class="p">)</span><span class="o">.</span><span class="n">fuse</span><span class="p">(</span><span class="n">hS</span><span class="p">)</span> <span class="p">)</span>

<span class="c1">#Part.show(hS.mirror(o, y).fuse(hSr))</span>
<span class="c1">#Part.show(hSr.mirror(o, y).fuse(hS))</span>

<span class="n">hSrm</span> <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">makeRevolution</span><span class="p">(</span><span class="n">Part</span><span class="o">.</span><span class="n">Arc</span><span class="p">(</span><span class="o">-</span><span class="mi">10</span><span class="o">*</span><span class="n">z</span><span class="p">,</span> <span class="o">-</span><span class="mi">10</span><span class="o">*</span><span class="n">x</span><span class="p">,</span> <span class="mi">10</span><span class="o">*</span><span class="n">z</span><span class="p">),</span>
           <span class="n">arc</span><span class="o">.</span><span class="n">FirstParameter</span><span class="p">,</span> <span class="n">arc</span><span class="o">.</span><span class="n">LastParameter</span><span class="p">,</span> <span class="mi">180</span><span class="p">,</span> <span class="n">o</span><span class="p">,</span> <span class="n">z</span><span class="p">,</span> <span class="n">Part</span><span class="o">.</span><span class="n">Solid</span><span class="p">)</span>
<span class="k">print</span><span class="p">(</span> <span class="n">hSrm</span><span class="o">.</span><span class="n">isClosed</span><span class="p">()</span> <span class="p">)</span>   <span class="c1"># True</span>
<span class="k">print</span><span class="p">(</span> <span class="n">hSrm</span><span class="o">.</span><span class="n">isValid</span><span class="p">()</span> <span class="p">)</span>    <span class="c1"># True</span>
<span class="k">print</span><span class="p">(</span> <span class="n">hSrm</span><span class="o">.</span><span class="n">ShapeType</span> <span class="p">)</span>    <span class="c1"># Solid</span>
<span class="c1">#Part.show(hSrm)</span>
<span class="c1">#Part.show(hSrm.fuse(hS))</span>
<span class="n">hS2</span> <span class="o">=</span> <span class="n">hSm</span><span class="o">.</span><span class="n">fuse</span><span class="p">(</span><span class="n">hS</span><span class="p">)</span>
<span class="c1">#Part.show(hS2)</span>

<span class="n">hSm1</span> <span class="o">=</span> <span class="n">hS</span><span class="o">.</span><span class="n">mirror</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">x</span><span class="p">)</span>
<span class="k">print</span><span class="p">(</span> <span class="n">hSm1</span><span class="o">.</span><span class="n">isClosed</span><span class="p">()</span> <span class="p">)</span>  <span class="c1"># True</span>
<span class="k">print</span><span class="p">(</span> <span class="n">hSm1</span><span class="o">.</span><span class="n">isValid</span><span class="p">()</span> <span class="p">)</span>   <span class="c1"># True</span>
<span class="k">print</span><span class="p">(</span> <span class="n">hSm1</span><span class="o">.</span><span class="n">ShapeType</span> <span class="p">)</span>   <span class="c1"># Solid</span>
<span class="c1">#Part.show(hSm1)</span>
<span class="c1">#Part.show(hS.fuse(hSm1) )</span>

<span class="c1"># STILL TO FIX BELOW</span>
<span class="c1"># this produces a flat disk, which</span>
<span class="c1"># LOOKS TO ME LIKE A BUG OR LIMIT ON ANGLE, OR UNDOCUMENTED AND UNCHECKED FEATURE</span>
<span class="n">hSm</span> <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">makeRevolution</span><span class="p">(</span><span class="n">arc</span><span class="p">,</span>
           <span class="n">arc</span><span class="o">.</span><span class="n">FirstParameter</span><span class="p">,</span> <span class="n">arc</span><span class="o">.</span><span class="n">LastParameter</span><span class="p">,</span> <span class="o">-</span><span class="mi">180</span><span class="p">,</span> <span class="n">o</span><span class="p">,</span> <span class="n">z</span><span class="p">,</span> <span class="n">Part</span><span class="o">.</span><span class="n">Solid</span><span class="p">)</span>
<span class="c1">#Part.show(hSm)</span>

<span class="c1"># NEXT SHOULD BE SAME AS ABOVE (reversing signs on 180 and z)</span>
<span class="c1"># this works but has some anomolies across the flat face</span>
<span class="n">hSm</span> <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">makeRevolution</span><span class="p">(</span><span class="n">arc</span><span class="p">,</span>
           <span class="n">arc</span><span class="o">.</span><span class="n">FirstParameter</span><span class="p">,</span> <span class="n">arc</span><span class="o">.</span><span class="n">LastParameter</span><span class="p">,</span> <span class="mi">180</span><span class="p">,</span> <span class="n">o</span><span class="p">,</span> <span class="o">-</span><span class="n">z</span><span class="p">,</span> <span class="n">Part</span><span class="o">.</span><span class="n">Solid</span><span class="p">)</span>

<span class="c1">#Part.show(hSm)</span>
<span class="k">print</span><span class="p">(</span> <span class="n">hSm</span><span class="o">.</span><span class="n">isClosed</span><span class="p">()</span> <span class="p">)</span>  <span class="c1">#True</span>
<span class="k">print</span><span class="p">(</span> <span class="n">hSm</span><span class="o">.</span><span class="n">isValid</span><span class="p">()</span> <span class="p">)</span>   <span class="c1">#False  but  ???</span>


<span class="n">Part</span><span class="o">.</span><span class="n">makeShell</span><span class="p">(</span><span class="n">hSm</span><span class="o">.</span><span class="n">Faces</span><span class="p">)</span><span class="o">.</span><span class="n">isValid</span><span class="p">()</span>  <span class="c1">#False but ???</span>
<span class="n">shellm</span> <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">makeShell</span><span class="p">(</span><span class="n">hSm</span><span class="o">.</span><span class="n">Faces</span><span class="p">)</span>
<span class="n">shellm</span><span class="o">.</span><span class="n">isValid</span><span class="p">()</span>
<span class="c1">#Part.makeShell([hSm.Faces]).isValid()RuntimeError: check failed, shape may be empty</span>
<span class="c1">#Part.show(shellm)</span>
<span class="c1">#hSm = hS.mirror(o, x)</span>
<span class="n">HS</span> <span class="o">=</span> <span class="n">hS</span><span class="o">.</span><span class="n">fuse</span><span class="p">([</span><span class="n">hSm</span><span class="p">])</span>   <span class="c1"># FAILS USING GUI UNION TOO</span>
<span class="c1">#testEqual(s, HS.cleaned(), debug = True)</span>
<span class="c1">#Part.show(HS)</span>
<span class="c1"># this misses a quarter HS = hS.fuse(hS.mirror(o, x))</span>
</pre></div>
</div>
<div class="highlight-none"><div class="highlight"><pre>True
True
Solid
True
True
Solid
True
True
Solid
True
False
</pre></div>
</div>
<p><code class="xref py py-func docutils literal"><span class="pre">Part.makeRevolution()</span></code> and Shape method <code class="xref py py-func docutils literal"><span class="pre">revolve()</span></code>
use different approaches.
Shape method <code class="xref py py-func docutils literal"><span class="pre">revolve()</span></code> uses BRepPrimAPI_MakeRevol which accepts
a shape as input. <code class="xref py py-func docutils literal"><span class="pre">Part.makeRevolution()</span></code> accepts a GeomCurve.</p>
<p>So Shape method <code class="xref py py-func docutils literal"><span class="pre">revolve()</span></code> using accepts a wider range of
objects: with a vertex it creates an edge;
with an edge it creates a face;
with a wire it creates a shell;
with a face it creates a solid;
with a shell it creates a compound solid.</p>
<p>On the other hand, <code class="xref py py-func docutils literal"><span class="pre">Part.makeRevolution()</span></code> has some flexibility on
what the output will be.</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">arc</span> <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">Arc</span><span class="p">(</span><span class="o">-</span><span class="mi">10</span><span class="o">*</span><span class="n">z</span><span class="p">,</span> <span class="mi">10</span><span class="o">*</span><span class="n">x</span><span class="p">,</span> <span class="mi">10</span><span class="o">*</span><span class="n">z</span><span class="p">)</span>
<span class="n">arcShapeEdge</span> <span class="o">=</span> <span class="n">arc</span><span class="o">.</span><span class="n">toShape</span><span class="p">()</span>
<span class="k">print</span><span class="p">(</span> <span class="n">arcShapeEdge</span><span class="o">.</span><span class="n">ShapeType</span> <span class="p">)</span>  <span class="c1">#Edge</span>

<span class="n">arcShapeWire</span> <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">Wire</span><span class="p">(</span><span class="n">arcShapeEdge</span><span class="p">)</span>
<span class="k">print</span><span class="p">(</span> <span class="n">arcShapeWire</span><span class="o">.</span><span class="n">ShapeType</span> <span class="p">)</span>  <span class="c1">#Wire</span>

<span class="c1"># makeRevolution</span>
<span class="n">s0</span> <span class="o">=</span><span class="n">Part</span><span class="o">.</span><span class="n">makeRevolution</span><span class="p">(</span><span class="n">arc</span><span class="p">,</span> <span class="n">arc</span><span class="o">.</span><span class="n">FirstParameter</span><span class="p">,</span> <span class="n">arc</span><span class="o">.</span><span class="n">LastParameter</span><span class="p">,</span>
              <span class="mi">360</span><span class="p">,</span> <span class="n">o</span><span class="p">,</span> <span class="n">z</span><span class="p">,</span> <span class="n">Part</span><span class="o">.</span><span class="n">Solid</span><span class="p">)</span>

<span class="k">print</span><span class="p">(</span> <span class="n">s0</span><span class="o">.</span><span class="n">ShapeType</span> <span class="p">)</span>  <span class="c1">#Solid</span>
<span class="n">testEqual</span><span class="p">(</span><span class="n">s</span><span class="p">,</span> <span class="n">s0</span><span class="p">)</span>
</pre></div>
</div>
<div class="highlight-none"><div class="highlight"><pre>Edge
Wire
Solid
</pre></div>
</div>
<p>From a vertex revolve to create an edge, and then revolve again to give a sphere.
This works if the vertex is revolved 180 degrees to give a half circle, and
that is revolved 360 degrees to give the sphere:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">zp</span> <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">Point</span><span class="p">(</span><span class="n">Vector</span><span class="p">(</span><span class="mi">10</span><span class="p">,</span><span class="mi">0</span><span class="p">,</span><span class="mi">0</span><span class="p">))</span><span class="o">.</span><span class="n">toShape</span><span class="p">()</span>
<span class="k">print</span><span class="p">(</span> <span class="n">zp</span><span class="o">.</span><span class="n">ShapeType</span> <span class="p">)</span> <span class="c1">#Vertex</span>

<span class="n">s1</span> <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">makeSolid</span><span class="p">(</span><span class="n">Part</span><span class="o">.</span><span class="n">makeShell</span><span class="p">([</span><span class="n">zp</span><span class="o">.</span><span class="n">revolve</span><span class="p">(</span><span class="n">o</span><span class="p">,</span><span class="n">z</span><span class="p">,</span><span class="mi">180</span><span class="p">)</span><span class="o">.</span><span class="n">revolve</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">x</span><span class="p">,</span> <span class="mi">360</span><span class="p">)]))</span>
<span class="c1">#Part.show(s1)</span>
<span class="k">print</span><span class="p">(</span> <span class="n">s1</span><span class="o">.</span><span class="n">ShapeType</span> <span class="p">)</span>  <span class="c1">#Solid</span>
<span class="k">print</span><span class="p">(</span> <span class="n">s1</span><span class="o">.</span><span class="n">isClosed</span><span class="p">()</span> <span class="p">)</span> <span class="c1">#True</span>
<span class="k">print</span><span class="p">(</span> <span class="n">s1</span><span class="o">.</span><span class="n">isValid</span><span class="p">()</span>  <span class="p">)</span> <span class="c1">#True</span>
<span class="n">testEqual</span><span class="p">(</span><span class="n">s</span><span class="p">,</span> <span class="n">s1</span><span class="p">)</span>
</pre></div>
</div>
<div class="highlight-none"><div class="highlight"><pre>Vertex
Solid
True
True
</pre></div>
</div>
<p>However, it fails if the rotations are 360 first then 180. This is possibly
because of the issue mentioned in the revolve doc, that rotation works best
about an axis that goes though vertexes.
The problem is more than anomolies suggested in the doc.</p>
<p>From an edge revolve create a face.
This works to give solid (but isClosed() seems wrong):</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">zz</span> <span class="o">=</span> <span class="n">arcShapeEdge</span><span class="o">.</span><span class="n">revolve</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">z</span><span class="p">,</span> <span class="mi">360</span><span class="p">)</span>
<span class="c1">#Part.show(zz)</span>
<span class="k">print</span><span class="p">(</span> <span class="n">zz</span><span class="o">.</span><span class="n">ShapeType</span>  <span class="p">)</span>  <span class="c1">#Face</span>
<span class="k">print</span><span class="p">(</span> <span class="n">zz</span><span class="o">.</span><span class="n">isClosed</span><span class="p">()</span> <span class="p">)</span>  <span class="c1">#False #Looks like a BUG.</span>
<span class="k">print</span><span class="p">(</span> <span class="n">zz</span><span class="o">.</span><span class="n">isValid</span><span class="p">()</span>  <span class="p">)</span>  <span class="c1">#True</span>
<span class="n">s2</span> <span class="o">=</span> <span class="n">Part</span><span class="o">.</span><span class="n">makeSolid</span><span class="p">(</span><span class="n">Part</span><span class="o">.</span><span class="n">makeShell</span><span class="p">([</span><span class="n">zz</span><span class="p">]))</span>
<span class="k">print</span><span class="p">(</span> <span class="n">s2</span><span class="o">.</span><span class="n">ShapeType</span>  <span class="p">)</span>  <span class="c1">#Solid</span>
<span class="k">print</span><span class="p">(</span> <span class="n">s2</span><span class="o">.</span><span class="n">isClosed</span><span class="p">()</span> <span class="p">)</span>  <span class="c1">#True</span>
<span class="k">print</span><span class="p">(</span> <span class="n">s2</span><span class="o">.</span><span class="n">isValid</span><span class="p">()</span>  <span class="p">)</span>  <span class="c1">#True</span>
<span class="k">print</span><span class="p">(</span> <span class="nb">len</span><span class="p">(</span><span class="n">s2</span><span class="o">.</span><span class="n">Solids</span><span class="p">)</span> <span class="p">)</span> <span class="c1"># 1</span>
<span class="c1">#Part.show(s2)</span>
<span class="n">testEqual</span><span class="p">(</span><span class="n">s</span><span class="p">,</span> <span class="n">s2</span><span class="p">)</span>
</pre></div>
</div>
<div class="highlight-none"><div class="highlight"><pre>Face
False
True
Solid
True
True
1
</pre></div>
</div>
<p>For a wire revolve creates a shell:</p>
<div class="highlight-python"><div class="highlight"><pre><span class="n">ar</span> <span class="o">=</span> <span class="n">arcShapeWire</span><span class="o">.</span><span class="n">revolve</span><span class="p">(</span><span class="n">o</span><span class="p">,</span> <span class="n">z</span><span class="p">,</span> <span class="mi">360</span><span class="p">)</span>
<span class="k">print</span><span class="p">(</span> <span class="n">ar</span><span class="o">.</span><span class="n">ShapeType</span>  <span class="p">)</span> <span class="c1">#Shell</span>
<span class="k">print</span><span class="p">(</span> <span class="n">ar</span><span class="o">.</span><span class="n">isClosed</span><span class="p">()</span> <span class="p">)</span> <span class="c1">#True</span>
<span class="k">print</span><span class="p">(</span> <span class="n">ar</span><span class="o">.</span><span class="n">isValid</span><span class="p">()</span>  <span class="p">)</span> <span class="c1">#True</span>

<span class="n">s3</span> <span class="o">=</span>  <span class="n">Part</span><span class="o">.</span><span class="n">makeSolid</span><span class="p">(</span><span class="n">ar</span><span class="p">)</span>
<span class="n">Part</span><span class="o">.</span><span class="n">show</span><span class="p">(</span><span class="n">s3</span><span class="p">)</span>
<span class="k">print</span><span class="p">(</span> <span class="n">s3</span><span class="o">.</span><span class="n">ShapeType</span>  <span class="p">)</span> <span class="c1">#Solid</span>
<span class="k">print</span><span class="p">(</span> <span class="n">s3</span><span class="o">.</span><span class="n">isClosed</span><span class="p">()</span> <span class="p">)</span> <span class="c1">#True</span>
<span class="k">print</span><span class="p">(</span> <span class="n">s3</span><span class="o">.</span><span class="n">isValid</span><span class="p">()</span>  <span class="p">)</span> <span class="c1">#True</span>
<span class="k">print</span><span class="p">(</span> <span class="nb">len</span><span class="p">(</span><span class="n">s3</span><span class="o">.</span><span class="n">Solids</span><span class="p">)</span> <span class="p">)</span> <span class="c1"># 1</span>
<span class="n">testEqual</span><span class="p">(</span><span class="n">s</span><span class="p">,</span> <span class="n">s3</span><span class="p">)</span>
</pre></div>
</div>
<div class="highlight-none"><div class="highlight"><pre>Shell
True
True
Solid
True
True
1
</pre></div>
</div>
<p>And 4 and 5 from post if they can be made to work</p>
</div>


          </div>
        </div>
      </div>
      <div class="sphinxsidebar" role="navigation" aria-label="main navigation">
        <div class="sphinxsidebarwrapper">
  <h4>Previous topic</h4>
  <p class="topless"><a href="circle.html"
                        title="previous chapter">Circle</a></p>
  <h4>Next topic</h4>
  <p class="topless"><a href="ellipse.html"
                        title="next chapter">Ellipse</a></p>
  <div role="note" aria-label="source link">
    <h3>This Page</h3>
    <ul class="this-page-menu">
      <li><a href="../_sources/Primitives/sphere.txt"
            rel="nofollow">Show Source</a></li>
    </ul>
   </div>
<div id="searchbox" style="display: none" role="search">
  <h3>Quick search</h3>
    <form class="search" action="../search.html" method="get">
      <input type="text" name="q" />
      <input type="submit" value="Go" />
      <input type="hidden" name="check_keywords" value="yes" />
      <input type="hidden" name="area" value="default" />
    </form>
    <p class="searchtip" style="font-size: 90%">
    Enter search terms or a module, class or function name.
    </p>
</div>
<script type="text/javascript">$('#searchbox').show(0);</script>
        </div>
      </div>
      <div class="clearer"></div>
    </div>
    <div class="related" role="navigation" aria-label="related navigation">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="../genindex.html" title="General Index"
             >index</a></li>
        <li class="right" >
          <a href="ellipse.html" title="Ellipse"
             >next</a> |</li>
        <li class="right" >
          <a href="circle.html" title="Circle"
             >previous</a> |</li>
        <li class="nav-item nav-item-0"><a href="../index.html">EgFreeCAD 0.1 documentation</a> &raquo;</li>
          <li class="nav-item nav-item-1"><a href="index.html" >Primitive Examples</a> &raquo;</li> 
      </ul>
    </div>
    <div class="footer" role="contentinfo">
        &copy; Copyright 2018, 2019, Paul Gilbert.
      Last updated on May 21, 2019.
      Created using <a href="http://sphinx-doc.org/">Sphinx</a> 1.3.6.
    </div>
  </body>
</html>